# Generated by Django 5.0.3 on 2024-03-25 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=200)),
                ('Modelo', models.CharField(max_length=200)),
                ('Kilometros', models.IntegerField()),
                ('Año', models.IntegerField()),
                ('Color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=200)),
                ('Autos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.autos')),
            ],
        ),
    ]
