# Generated by Django 5.0.3 on 2024-03-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.IntegerField()),
                ('Mensaje', models.TextField(max_length=200)),
            ],
        ),
    ]
